#GET all
GET http://localhost:8080/produtos

#GET by ID
GET http://localhost:8080/produtos/1

POST http://localhost:8080/produtos HTTP/1.1
Content-Type: application/json
{
    "descricao": "Teclado Mecânico Gamer HyperX Alloy Origins 60%, RGB, USB, HyperX Red Switch, Design Compacto, Anti-Ghosting, US, Preto - HKBO1S-RB-USG",
    "preco": "R$ 599,90"
}

PUT http://localhost:8080/produtos/43 HTTP/1.1
Content-Type: application/json

{
    "descricao": "Teclado Gamer HyperX Alloy Core, RGB, ABNT2 - HX-KB5ME2-BR",
    "preco": "R$ 399,90"
}

DELETE http://localhost:8080/produtos/36